language: php

sudo: false

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - 7.3

env:
  matrix:
    - LARAVEL=5.4
    - LARAVEL=5.5
    - LARAVEL=5.6
    - LARAVEL=5.7
    - LARAVEL=5.8
    - LARAVEL=6.0

matrix:
  exclude:
    - php: 5.6
      env: LARAVEL=5.5
    - php: 5.6
      env: LARAVEL=5.6
    - php: 5.6
      env: LARAVEL=5.7
    - php: 5.6
      env: LARAVEL=5.8
    - php: 5.6
      env: LARAVEL=6.0
    - php: 7.0
      env: LARAVEL=5.6
    - php: 7.0
      env: LARAVEL=5.7
    - php: 7.0
      env: LARAVEL=5.8
    - php: 7.0
      env: LARAVEL=6.0
    - php: 7.1
      env: LARAVEL=6.0

before_script:
  - export COMPOSER=tests/composer-$LARAVEL.json
  - travis_retry composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover=coverage.clover

after_script:
  - bash -c 'if [ "${TRAVIS_PHP_VERSION:0:4}" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [ "${TRAVIS_PHP_VERSION:0:4}" != "hhvm-nightly" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
